name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get version from tag
      run: |
        # Extract version from tag (remove 'v' prefix if present)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Building version: $VERSION"

    - name: Build binary
      run: |
        # Build statically linked binary for Linux
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
          -ldflags="-w -s -X main.version=${VERSION} -X main.commit=${GITHUB_SHA} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          -o service-control-panel \
          ./cmd/service-control/

    - name: Verify binary
      run: |
        file service-control-panel
        ./service-control-panel -h 2>/dev/null || echo "Binary built successfully (no help flag)"

    - name: Create release archive
      run: |
        # Create a tar.gz archive with the binary
        tar -czf service-control-panel-${VERSION}-linux-amd64.tar.gz service-control-panel
        ls -la service-control-panel*

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          service-control-panel-${{ env.VERSION }}-linux-amd64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
