name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases

    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Get version from tag
      id: get_version
      run: |
        # Extract version from tag (remove 'v' prefix if present)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION for ${{ matrix.arch }}"

    - name: Build binary
      run: |
        # Build statically linked binary for Linux
        CGO_ENABLED=0 GOOS=linux GOARCH=${{ matrix.arch }} go build \
          -ldflags="-w -s -X main.version=${{ steps.get_version.outputs.version }} -X main.commit=${GITHUB_SHA} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          -o sysdwitch \
          ./cmd/sysdwitch/

    - name: Verify binary
      run: |
        file sysdwitch
        ./sysdwitch -h 2>/dev/null || echo "Binary built successfully (no help flag)"

    - name: Generate checksums
      run: |
        # Generate SHA256 checksums for verification
        sha256sum sysdwitch > sysdwitch-${{ steps.get_version.outputs.version }}-${{ matrix.arch }}-linux.sha256

    - name: Create source archives
      if: matrix.arch == 'amd64'  # Only create once, not per architecture
      run: |
        # Create source code archives
        git archive --format=tar.gz -o sysdwitch-${{ steps.get_version.outputs.version }}-source.tar.gz HEAD
        git archive --format=zip -o sysdwitch-${{ steps.get_version.outputs.version }}-source.zip HEAD
        ls -la sysdwitch-*source*

    - name: Upload release assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          sysdwitch#sysdwitch-${{ steps.get_version.outputs.version }}-${{ matrix.arch }}-linux
          sysdwitch-${{ steps.get_version.outputs.version }}-${{ matrix.arch }}-linux.sha256
          ${{ matrix.arch == 'amd64' && format('sysdwitch-{0}-source.tar.gz', steps.get_version.outputs.version) || '' }}
          ${{ matrix.arch == 'amd64' && format('sysdwitch-{0}-source.zip', steps.get_version.outputs.version) || '' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
